CREATE TABLE `MEMBER` (
	`MID`	NUMBER	NOT NULL,
	`MEMAIL`	VARCHAR2(100)	NOT NULL	COMMENT '@.',
	`MPWD`	VARCHAR2(20)	NOT NULL,
	`REG_DATE`	DATE	NOT NULL,
	`MNAME`	VARCHAR2(30)	NOT NULL,
	`MIP`	VARCHAR2(15)	NULL
);

CREATE TABLE `SERVEY_CONTENT` (
	`DDATE`	DATE	NOT NULL,
	`MID`	NUMBER	NOT NULL,
	`SER_1`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1',
	`SER_2`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1',
	`SER_3`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1',
	`SER_4`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1',
	`SER_5`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1',
	`SER_SCORE_1`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '100점 만점',
	`SER_CONTENT`	VARCHAR2(1000)	NULL
);

CREATE TABLE `SERVEY_DATE` (
	`DDATE`	DATE	NOT NULL,
	`MID`	NUMBER	NOT NULL,
	`DSERVEY`	VARCHAR(1)	NOT NULL	DEFAULT N	COMMENT 'Y/N'
);

CREATE TABLE `SCHEDULE` (
	`SNUM`	NUMBER	NOT NULL,
	`MID`	NUMBER	NOT NULL,
	`SCONTENT`	VARCHAR2(200)	NOT NULL,
	`SDATE_START`	DATE	NOT NULL,
	`SDATE_END`	DATE	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MID`
);

ALTER TABLE `SERVEY_CONTENT` ADD CONSTRAINT `PK_SERVEY_CONTENT` PRIMARY KEY (
	`DDATE`,
	`MID`
);

ALTER TABLE `SERVEY_DATE` ADD CONSTRAINT `PK_SERVEY_DATE` PRIMARY KEY (
	`DDATE`,
	`MID`
);

ALTER TABLE `SCHEDULE` ADD CONSTRAINT `PK_SCHEDULE` PRIMARY KEY (
	`SNUM`,
	`MID`
);

ALTER TABLE `SERVEY_CONTENT` ADD CONSTRAINT `FK_SERVEY_DATE_TO_SERVEY_CONTENT_1` FOREIGN KEY (
	`DDATE`
)
REFERENCES `SERVEY_DATE` (
	`DDATE`
);

ALTER TABLE `SERVEY_CONTENT` ADD CONSTRAINT `FK_SERVEY_DATE_TO_SERVEY_CONTENT_2` FOREIGN KEY (
	`MID`
)
REFERENCES `SERVEY_DATE` (
	`MID`
);

ALTER TABLE `SERVEY_DATE` ADD CONSTRAINT `FK_MEMBER_TO_SERVEY_DATE_1` FOREIGN KEY (
	`MID`
)
REFERENCES `MEMBER` (
	`MID`
);

ALTER TABLE `SCHEDULE` ADD CONSTRAINT `FK_MEMBER_TO_SCHEDULE_1` FOREIGN KEY (
	`MID`
)
REFERENCES `MEMBER` (
	`MID`
);

