DROP TABLE "SERVEY_CONTENT";
DROP TABLE "SERVEY_DATE";
DROP TABLE "SCHEDULE";
DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MID"	NUMBER		NOT NULL,
	"MEMAIL"	VARCHAR2(100)		NOT NULL,
	"MPWD"	VARCHAR2(20)		NOT NULL,
	"REG_DATE"	DATE		NOT NULL,
	"MNAME"	VARCHAR2(30)		NOT NULL,
	"MIP"	VARCHAR2(15)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMAIL" IS '@.';

CREATE TABLE "SERVEY_CONTENT" (
	"DDATE"	DATE		NOT NULL,
	"MID"	NUMBER		NOT NULL,
	"SER_1"	NUMBER	DEFAULT 0	NOT NULL,
	"SER_2"	NUMBER	DEFAULT 0	NOT NULL,
	"SER_3"	NUMBER	DEFAULT 0	NOT NULL,
	"SER_4"	NUMBER	DEFAULT 0	NOT NULL,
	"SER_5"	NUMBER	DEFAULT 0	NOT NULL,
	"SER_SCORE_1"	NUMBER	DEFAULT 0	NOT NULL,
	"SER_CONTENT"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "SERVEY_CONTENT"."SER_1" IS '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1';

COMMENT ON COLUMN "SERVEY_CONTENT"."SER_2" IS '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1';

COMMENT ON COLUMN "SERVEY_CONTENT"."SER_3" IS '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1';

COMMENT ON COLUMN "SERVEY_CONTENT"."SER_4" IS '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1';

COMMENT ON COLUMN "SERVEY_CONTENT"."SER_5" IS '매우 만족 : 5, 만족 : 4, 보통 : 3, 불만족 : 2, 매우 불만족 : 1';

COMMENT ON COLUMN "SERVEY_CONTENT"."SER_SCORE_1" IS '10점 만점';

CREATE TABLE "SERVEY_DATE" (
	"DDATE"	DATE		NOT NULL,
	"MID"	NUMBER		NOT NULL,
	"DSERVEY"	VARCHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "SERVEY_DATE"."DSERVEY" IS 'Y/N';

CREATE TABLE "SCHEDULE" (
	"SNUM"	NUMBER		NOT NULL,
	"MID"	NUMBER		NOT NULL,
	"SCONTENT"	VARCHAR2(200)		NOT NULL,
	"SDATE"	DATE		NOT NULL,
	"SDATE_START"	DATE		NULL,
	"SDATE_END"	DATE		NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MID"
);

ALTER TABLE "SERVEY_CONTENT" ADD CONSTRAINT "PK_SERVEY_CONTENT" PRIMARY KEY (
	"DDATE",
	"MID"
);


ALTER TABLE "SERVEY_DATE" ADD CONSTRAINT "PK_SERVEY_DATE" PRIMARY KEY (
	"DDATE",
	"MID"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY (
	"SNUM",
	"MID"
);

ALTER TABLE "SERVEY_CONTENT" ADD CONSTRAINT "FK_SERVEY_DATE_TO_CONTENT_1" FOREIGN KEY (
	"DDATE","MID"
)
REFERENCES "SERVEY_DATE" (
	"DDATE","MID"
);

ALTER TABLE "SERVEY_DATE" ADD CONSTRAINT "FK_MEMBER_TO_SERVEY_DATE_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "FK_MEMBER_TO_SCHEDULE_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);